config/routes.rb
Rails.application.routes.draw do

  resources :temps
  
  get 'user_tasks/index'
  get 'lab1/index'
  get 'lab1/login'
  get 'lab1/invoice'
  get 'lab1/maint'
  get 'lab1/setting'
  get 'lab1/tax'
  get 'lab1/tasklist'

  get 'user_tasks/index'
  
  root 'sessions#new'
  
  get 'admin/index'
  get 'admin/showUserLogs'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users
  resources :tasks
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/temp.rb
class Temp < ApplicationRecord
end

app/controllers/temps_controller.rb
class TempsController < ApplicationController
  before_action :set_temp, only: [:show, :edit, :update, :destroy]

  # GET /temps
  # GET /temps.json
  def index
    @temps = Temp.all
  end

  # GET /temps/1
  # GET /temps/1.json
  def show
  end

  # GET /temps/new
  def new
    @temp = Temp.new
  end

  # GET /temps/1/edit
  def edit
  end

  # POST /temps
  # POST /temps.json
  def create
    @temp = Temp.new(temp_params)

    respond_to do |format|
      if @temp.save
        format.html { redirect_to @temp, notice: 'Temp was successfully created.' }
        format.json { render :show, status: :created, location: @temp }
      else
        format.html { render :new }
        format.json { render json: @temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temps/1
  # PATCH/PUT /temps/1.json
  def update
    respond_to do |format|
      if @temp.update(temp_params)
        format.html { redirect_to @temp, notice: 'Temp was successfully updated.' }
        format.json { render :show, status: :ok, location: @temp }
      else
        format.html { render :edit }
        format.json { render json: @temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temps/1
  # DELETE /temps/1.json
  def destroy
    @temp.destroy
    respond_to do |format|
      format.html { redirect_to temps_url, notice: 'Temp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temp
      @temp = Temp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temp_params
      params.require(:temp).permit(:id, :name, :desc)
    end
end

app/helpers/temps_helper.rb
module TempsHelper
end

app/views/temps/_form.html.erb
<%= form_with(model: temp, local: true) do |form| %>
  <% if temp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(temp.errors.count, "error") %> prohibited this temp from being saved:</h2>

      <ul>
      <% temp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/temps/edit.html.erb
<h1>Editing Temp</h1>

<%= render 'form', temp: @temp %>

<%= link_to 'Show', @temp %> |
<%= link_to 'Back', temps_path %>

app/views/temps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Temps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temps.each do |temp| %>
      <tr>
        <td><%= temp.id %></td>
        <td><%= temp.name %></td>
        <td><%= temp.desc %></td>
        <td><%= link_to 'Show', temp %></td>
        <td><%= link_to 'Edit', edit_temp_path(temp) %></td>
        <td><%= link_to 'Destroy', temp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temp', new_temp_path %>

app/views/temps/new.html.erb
<h1>New Temp</h1>

<%= render 'form', temp: @temp %>

<%= link_to 'Back', temps_path %>

app/views/temps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @temp.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @temp.desc %>
</p>

<%= link_to 'Edit', edit_temp_path(@temp) %> |
<%= link_to 'Back', temps_path %>